In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [4]:
house = pd.read_csv('housing.csv')
house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [5]:
X = house.drop('median_house_value', axis=1)
y = house.median_house_value

In [6]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [7]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [8]:
X_train , X_test, y_train , y_test = train_test_split(X,y ,test_size = 0.2, random_state = 121)

In [9]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
5800,-118.24,34.15,7.0,2063.0,670.0,1892.0,643.0,1.7301,<1H OCEAN
601,-122.08,37.70,25.0,3402.0,758.0,1645.0,710.0,3.4934,NEAR BAY
10379,-117.64,33.65,4.0,6842.0,1512.0,3256.0,1439.0,5.4132,<1H OCEAN
20405,-118.88,34.21,26.0,1590.0,196.0,654.0,199.0,6.5851,<1H OCEAN
7170,-118.19,34.06,37.0,1715.0,456.0,2052.0,440.0,2.3125,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
19198,-122.69,38.44,31.0,1808.0,315.0,691.0,280.0,3.8583,<1H OCEAN
3583,-118.55,34.23,25.0,4409.0,1018.0,4579.0,1010.0,2.8727,<1H OCEAN
18497,-121.54,36.99,27.0,2361.0,449.0,1782.0,397.0,3.2614,INLAND
4565,-118.26,34.07,40.0,680.0,273.0,995.0,249.0,2.2607,<1H OCEAN
11586,-118.01,33.79,30.0,2460.0,403.0,1277.0,395.0,5.4372,<1H OCEAN

In [10]:
y_train

5800     202300.0
601      209900.0
10379    216600.0
20405    300000.0
7170     116100.0
           ...
19198    193200.0
3583     245100.0
18497    305000.0
4565     165600.0
11586    223200.0
Name: median_house_value, Length: 16512, dtype: float64

In [11]:
y_test

16818    262000.0
18306    463700.0
549      254200.0
4239     434400.0
6084     188300.0
           ...
6460     272600.0
18375    362700.0
11212    182900.0
20291    187300.0
6340     186700.0
Name: median_house_value, Length: 4128, dtype: float64

In [12]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
16818,-122.46,37.65,16.0,8676.0,1633.0,5130.0,1574.0,4.8096,NEAR OCEAN
18306,-122.11,37.43,35.0,3905.0,565.0,1562.0,553.0,7.3130,NEAR BAY
549,-122.25,37.77,52.0,2156.0,458.0,872.0,445.0,3.2685,NEAR BAY
4239,-118.32,34.11,42.0,2462.0,543.0,857.0,482.0,4.0833,<1H OCEAN
6084,-117.89,34.09,36.0,1811.0,320.0,1005.0,332.0,5.5629,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
6460,-118.05,34.10,36.0,1606.0,318.0,889.0,294.0,4.7931,INLAND
18375,-121.85,37.22,21.0,6203.0,798.0,2494.0,800.0,7.7201,<1H OCEAN
11212,-117.91,33.82,29.0,1444.0,326.0,1038.0,271.0,2.3843,<1H OCEAN
20291,-119.19,34.17,35.0,4276.0,767.0,3295.0,708.0,4.2583,NEAR OCEAN
6340,-117.90,33.98,20.0,9893.0,2283.0,7228.0,2159.0,3.2530,<1H OCEAN

In [13]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [14]:
X['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [15]:
(X['ocean_proximity'].value_counts() / X.shape[0]) * 100

ocean_proximity
<1H OCEAN     44.263566
INLAND        31.739341
NEAR OCEAN    12.877907
NEAR BAY      11.094961
ISLAND         0.024225
Name: count, dtype: float64

In [16]:
(X_train['ocean_proximity'].value_counts() / X_train.shape[0]) *100

ocean_proximity
<1H OCEAN     44.507025
INLAND        31.686047
NEAR OCEAN    12.808866
NEAR BAY      10.973837
ISLAND         0.024225
Name: count, dtype: float64

In [17]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
16818,-122.46,37.65,16.0,8676.0,1633.0,5130.0,1574.0,4.8096,NEAR OCEAN
18306,-122.11,37.43,35.0,3905.0,565.0,1562.0,553.0,7.3130,NEAR BAY
549,-122.25,37.77,52.0,2156.0,458.0,872.0,445.0,3.2685,NEAR BAY
4239,-118.32,34.11,42.0,2462.0,543.0,857.0,482.0,4.0833,<1H OCEAN
6084,-117.89,34.09,36.0,1811.0,320.0,1005.0,332.0,5.5629,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
6460,-118.05,34.10,36.0,1606.0,318.0,889.0,294.0,4.7931,INLAND
18375,-121.85,37.22,21.0,6203.0,798.0,2494.0,800.0,7.7201,<1H OCEAN
11212,-117.91,33.82,29.0,1444.0,326.0,1038.0,271.0,2.3843,<1H OCEAN
20291,-119.19,34.17,35.0,4276.0,767.0,3295.0,708.0,4.2583,NEAR OCEAN
6340,-117.90,33.98,20.0,9893.0,2283.0,7228.0,2159.0,3.2530,<1H OCEAN

In [18]:
(X_test['ocean_proximity'].value_counts() / X_test.shape[0]) *100

ocean_proximity
<1H OCEAN     43.289729
INLAND        31.952519
NEAR OCEAN    13.154070
NEAR BAY      11.579457
ISLAND         0.024225
Name: count, dtype: float64

In [19]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [20]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [21]:
s = StratifiedShuffleSplit(n_splits = 10 , test_size = 0.2 , random_state = 123)
s

StratifiedShuffleSplit(n_splits=10, random_state=123, test_size=0.2,
            train_size=None)

In [22]:
s.split(X,X['ocean_proximity'])

In [23]:
for i in s.split(X,X['ocean_proximity']):
    print(i)

(array([ 5015,  3769,  4895, ...,  5040, 15540, 16420], shape=(16512,)), array([15606,  1721, 10372, ..., 17953,  4683, 20144], shape=(4128,)))
(array([ 3239,  6480,  1242, ...,  5607,  6186, 15453], shape=(16512,)), array([20638, 19583, 15351, ..., 10120, 17973,  8380], shape=(4128,)))
(array([17201,  9158, 18204, ..., 16694,  4065,  7006], shape=(16512,)), array([12059,   452, 12482, ...,  3445, 20047, 10784], shape=(4128,)))
(array([12213, 15033, 13893, ...,  3346,  9067,  9779], shape=(16512,)), array([18842, 20635,   232, ...,  6419, 20335, 19781], shape=(4128,)))
(array([20012, 19870,  8754, ...,  4096,  1904, 13255], shape=(16512,)), array([ 7009,  5307, 15015, ...,  7692,  8119,  7242], shape=(4128,)))
(array([ 2660,  1682, 10437, ..., 13962,  8584,  7942], shape=(16512,)), array([11033, 17379, 15105, ...,  7951, 13164,  1645], shape=(4128,)))
(array([ 7969, 13495, 18977, ..., 15965, 18842,  5383], shape=(16512,)), array([ 9169,  4885, 20218, ...,  1540,  1647,  2744], shape=(4128,)))
(array([14089,  7352, 19267, ...,    88,  8359,  1728], shape=(16512,)), array([15931, 11539,  3677, ..., 14208, 13555, 10228], shape=(4128,)))
(array([16966, 13874, 16253, ..., 17502,  7486, 14118], shape=(16512,)), array([20469,  2974, 14298, ..., 20570, 17002, 16318], shape=(4128,)))
(array([14635, 18765,  5557, ..., 18516,  3855, 16235], shape=(16512,)), array([ 3589, 13994, 17178, ..., 11694, 20603, 14310], shape=(4128,)))

In [24]:
c = 1
for train_idx, test_idx in s.split(X, X['ocean_proximity']):
    print(f"split_no ----> {c} ")
    print(f"train_idx: {train_idx}")
    print(f"test_idx: {test_idx}")
    print()
    c += 1

split_no ----> 1
train_idx: [ 5015  3769  4895 ...  5040 15540 16420]
test_idx: [15606  1721 10372 ... 17953  4683 20144]

split_no ----> 2
train_idx: [ 3239  6480  1242 ...  5607  6186 15453]
test_idx: [20638 19583 15351 ... 10120 17973  8380]

split_no ----> 3
train_idx: [17201  9158 18204 ... 16694  4065  7006]
test_idx: [12059   452 12482 ...  3445 20047 10784]

split_no ----> 4
train_idx: [12213 15033 13893 ...  3346  9067  9779]
test_idx: [18842 20635   232 ...  6419 20335 19781]

split_no ----> 5
train_idx: [20012 19870  8754 ...  4096  1904 13255]
test_idx: [ 7009  5307 15015 ...  7692  8119  7242]

split_no ----> 6
train_idx: [ 2660  1682 10437 ... 13962  8584  7942]
test_idx: [11033 17379 15105 ...  7951 13164  1645]

split_no ----> 7
train_idx: [ 7969 13495 18977 ... 15965 18842  5383]
test_idx: [ 9169  4885 20218 ...  1540  1647  2744]

split_no ----> 8
train_idx: [14089  7352 19267 ...    88  8359  1728]
test_idx: [15931 11539  3677 ... 14208 13555 10228]

split_no ----> 9
train_idx: [16966 13874 16253 ... 17502  7486 14118]
test_idx: [20469  2974 14298 ... 20570 17002 16318]

split_no ----> 10
train_idx: [14635 18765  5557 ... 18516  3855 16235]
test_idx: [ 3589 13994 17178 ... 11694 20603 14310]

In [26]:
s = StratifiedShuffleSplit(n_splits = 1 , test_size = 0.2, random_state = 123)
s

StratifiedShuffleSplit(n_splits=1, random_state=123, test_size=0.2,
            train_size=None)

In [27]:
train_idx

array([14635, 18765,  5557, ..., 18516,  3855, 16235], shape=(16512,))

In [28]:
test_idx

array([ 3589, 13994, 17178, ..., 11694, 20603, 14310], shape=(4128,))

In [29]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [30]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [31]:
train_idx

array([14635, 18765,  5557, ..., 18516,  3855, 16235], shape=(16512,))

In [32]:
test_idx

array([ 3589, 13994, 17178, ..., 11694, 20603, 14310], shape=(4128,))

In [33]:
X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]
y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

In [34]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
14635,-117.21,32.80,34.0,1398.0,222.0,532.0,244.0,3.7102,NEAR OCEAN
18765,-122.27,40.53,17.0,2255.0,416.0,1171.0,411.0,2.8750,INLAND
5557,-118.41,33.94,45.0,2038.0,394.0,1086.0,387.0,4.7375,<1H OCEAN
3891,-118.56,34.22,34.0,1599.0,294.0,819.0,306.0,4.3194,<1H OCEAN
16391,-121.25,38.01,16.0,2397.0,501.0,1053.0,557.0,2.6994,INLAND
...,...,...,...,...,...,...,...,...,...
18880,-122.26,38.10,30.0,3317.0,1058.0,1794.0,990.0,1.1835,NEAR BAY
4626,-118.32,34.06,52.0,955.0,100.0,457.0,120.0,15.0001,<1H OCEAN
18516,-122.02,36.98,44.0,1153.0,238.0,657.0,219.0,3.2368,NEAR OCEAN
3855,-118.44,34.18,33.0,2127.0,414.0,1056.0,391.0,4.3750,<1H OCEAN
16235,-121.29,37.98,42.0,625.0,143.0,533.0,159.0,2.6250,INLAND

In [35]:
y_train

14635    289600.0
18765    129800.0
5557     289600.0
3891     197000.0
16391    112500.0
           ...
18880    133300.0
4626     500001.0
18516    212500.0
3855     286100.0
16235     65400.0
Name: median_house_value, Length: 16512, dtype: float64

In [36]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
3589,-118.45,34.25,34.0,2094.0,380.0,1207.0,380.0,5.2801,<1H OCEAN
13994,-116.99,34.88,23.0,6060.0,1165.0,2920.0,1072.0,3.1528,INLAND
17178,-122.47,37.51,15.0,4974.0,764.0,2222.0,774.0,6.7606,NEAR OCEAN
3079,-119.01,35.44,20.0,3458.0,651.0,1465.0,621.0,2.5806,INLAND
17291,-119.63,34.40,29.0,3865.0,814.0,1266.0,613.0,6.0069,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
9825,-121.91,36.62,30.0,724.0,167.0,325.0,155.0,3.3333,<1H OCEAN
19494,-121.01,37.67,37.0,2483.0,459.0,1072.0,445.0,3.0721,INLAND
11694,-117.98,33.89,18.0,2939.0,437.0,1278.0,435.0,7.1425,<1H OCEAN
20603,-121.54,39.13,18.0,4289.0,1021.0,2707.0,939.0,1.3375,INLAND
14310,-117.14,32.71,43.0,966.0,255.0,857.0,208.0,1.2841,NEAR OCEAN

In [37]:
y_test

3589     212300.0
13994     69000.0
17178    364300.0
3079      82500.0
17291    500001.0
           ...
9825     247900.0
19494    108100.0
11694    393700.0
20603     59600.0
14310     72000.0
Name: median_house_value, Length: 4128, dtype: float64

In [41]:
(X_train['ocean_proximity'].value_counts() / X_train.shape[0]) * 100

ocean_proximity
<1H OCEAN     44.264777
INLAND        31.740552
NEAR OCEAN    12.875484
NEAR BAY      11.094961
ISLAND         0.024225
Name: count, dtype: float64

In [42]:
(X_test['ocean_proximity'].value_counts() / X_test.shape[0]) * 100

ocean_proximity
<1H OCEAN     44.258721
INLAND        31.734496
NEAR OCEAN    12.887597
NEAR BAY      11.094961
ISLAND         0.024225
Name: count, dtype: float64

In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_squared_error, r2_score

house = pd.read_csv('housing.csv')

X = house.drop('median_house_value', axis = 1)
y = house.median_house_value

X_train,X_test, y_train, y_test = train_test_split(X,y,test_size= 0.1, random_state = 121)

num_pipeleine = Pipeline([
    ('impute', SimpleImputer(strategy = 'median')),
    ('scaler', StandardScaler())

])

cat_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy = "most_frequent")),
    ('encoding', OrdinalEncoder())
])

num_col = X.select_dtypes('float').columns
cat_col = X.select_dtypes('object').columns

final_pipeline = ColumnTransformer([
    ('num_pipeline', num_pipeleine, num_col),
    ('cat_pipeline', cat_pipeline, cat_col)
])

final_pipeline.fit(X_train)
X_train_tr = final_pipeline.transform(X_train)
X_test_tr = final_pipeline.transform(X_test)

model = LinearRegression()
model.fit(X_train_tr, y_train)

y_train_hat = model.predict(X_train_tr)
y_test_hat = model.predict(X_test_tr)

print(f"Training_error: {mean_squared_error(y_train, y_train_hat):.2f}")
print(f"Training_accuracy: {r2_score(y_train, y_train_hat):.2f}")
print()
print(f"Testing_error: {mean_squared_error(y_test, y_test_hat):.2f}")
print(f"Testiing_accuracy: {r2_score(y_test,y_test_hat):.2f}")

Training_error: 4856734253.80
Training_accuracy: 0.63

Testing_error: 4814422467.14
Testiing_accuracy: 0.64

In [48]:
y_train

4074     500001.0
8130     148100.0
11210    152400.0
13898     67400.0
10188    167500.0
           ...
19198    193200.0
3583     245100.0
18497    305000.0
4565     165600.0
11586    223200.0
Name: median_house_value, Length: 18576, dtype: float64

In [49]:
y_train_hat

array([517180.45222405, 176756.82786619, 211831.22523229, ...,
       179352.47913062, 155007.68761113, 270777.54534918], shape=(18576,))

    actual  [10, 34, 56, 78]
    predict [12, 33, 52, 65]