#### Pandas

### Data structure in Pandas
1.series -------> just like 1D array
2.Dataframe ------> Collection of series
3.Pannels -------> multidimensional data

INDEX: TWO TYPES OF INDEX ARE THERE:
1. default: we can not change it

2. Label: jo index show ho rahi ha and we can change index

slicing by using default: --> iloc --> int location / int index
                              
                              df.iloc [row.slicing , col.slicing ]

Slicing by using label : --> loc --> label index (voh index jo show ho rahi ha)

                             df.loc[row.slicing , col.slicing]

series

In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
arr = np.random.randint(23 , 56 , 20 )  # 23 to 55 ka beech mein random integers
arr

array([35, 27, 35, 55, 29, 26, 37, 49, 39, 30, 28, 23, 47, 38, 39, 38, 49,
       24, 46, 32], dtype=int32)

In [41]:
s1 = pd.Series([10,20,30,40,50,60])
s1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [42]:
arr

array([35, 27, 35, 55, 29, 26, 37, 49, 39, 30, 28, 23, 47, 38, 39, 38, 49,
       24, 46, 32], dtype=int32)

In [43]:
arr[0]   # first element

np.int32(35)

In [44]:
arr[:3]   # first 3 elements

array([35, 27, 35], dtype=int32)

In [45]:
s1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [46]:
s1[0]

np.int64(10)

In [47]:
s1[-2]      # ( default integer index ) ---> ye kaam tab hi karega jab defult index ho ,

KeyError: -2

In [ ]:
s1 = pd.Series([10,20,30,40,50,60], index=list("ABCDEF"))
s1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [ ]:
s1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [ ]:
s1[-1]

C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\149126795.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[-1]

np.int64(60)

In [ ]:
s1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [ ]:
s1[0]

C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.int64(10)

In [ ]:
s1['A']

np.int64(10)

In [ ]:
s1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [ ]:
s1[:3]

A    10
B    20
C    30
dtype: int64

In [ ]:
arr

array([38, 27, 40, 26, 25, 24, 50, 24, 52, 42, 30, 43, 49, 25, 23, 29, 40,
       46, 44, 47], dtype=int32)

In [ ]:
arr[:3]

array([38, 27, 40], dtype=int32)

In [ ]:
s1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [ ]:
s1[:3]

A    10
B    20
C    30
dtype: int64

In [ ]:
s1[:'D']

A    10
B    20
C    30
D    40
dtype: int64

In [ ]:
s1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [ ]:
s1['A'] = 100

In [ ]:
s1

A    100
B     20
C     30
D     40
E     50
F     60
dtype: int64

In [ ]:
s1[:3] = 20

In [ ]:
s1

A    20
B    20
C    20
D    40
E    50
F    60
dtype: int64

In [ ]:
arr + 10

array([48, 37, 50, 36, 35, 34, 60, 34, 62, 52, 40, 53, 59, 35, 33, 39, 50,
       56, 54, 57], dtype=int32)

In [ ]:
s1 + 10

A    30
B    30
C    30
D    50
E    60
F    70
dtype: int64

In [ ]:
s1/10

A    2.0
B    2.0
C    2.0
D    4.0
E    5.0
F    6.0
dtype: float64

In [ ]:
s1*10

A    200
B    200
C    200
D    400
E    500
F    600
dtype: int64

In [ ]:
s1

A    20
B    20
C    20
D    40
E    50
F    60
dtype: int64

In [ ]:
s1 < 30

A     True
B     True
C     True
D    False
E    False
F    False
dtype: bool

In [ ]:
s1[s1 < 30 ]

A    20
B    20
C    20
dtype: int64

In [ ]:
s1

A    20
B    20
C    20
D    40
E    50
F    60
dtype: int64

In [ ]:
s1.sum()

np.int64(210)

In [ ]:
s1.mean()

np.float64(35.0)

In [ ]:
s1

A    20
B    20
C    20
D    40
E    50
F    60
dtype: int64

In [ ]:
s2 = pd.Series([34,45,78,45,78], index = list("ABCDE"))
s2

A    34
B    45
C    78
D    45
E    78
dtype: int64

In [ ]:
s1 + s2

A     54.0
B     65.0
C     98.0
D     85.0
E    128.0
F      NaN
dtype: float64

Pandas Series – Interview Q&A Cheat Sheet
1️⃣ Basics

Q1: Pandas Series kya hai?
A: Series = 1D labeled array in Pandas. Data + Index (labels).

Q2: Series aur Numpy array mein difference kya hai?
A:

Numpy array: only numeric, index integer-based

Series: numeric/non-numeric data + custom labels (index) possible

Q3: Default index kya hai?
A: Jab custom index na diya ho, Pandas automatically 0,1,2,… integer index assign karta hai.

Q4: Custom index ka use kyun?
A: Data ko readable aur label-based access ke liye, jaise 'A','B','C' instead of 0,1,2

2️⃣ Indexing / Access

Q5: s[0] aur s['A'] mein kya difference?
A:

s[0] → integer position (default index)

s['A'] → label-based access (custom index 'A')

Q6: s[-1] hamesha last element return karega?
A:

Default index → last element return karega

Custom index → ERROR, kyunki -1 label exist nahi karta

Q7: .loc vs .iloc?
A:

.loc[label] → label-based access

.iloc[position] → position-based access

Q8: Negative indexing kaise kaam karta hai?
A:

Default integer index → last element = s[-1]

Custom index → use .iloc[-1]

3️⃣ Slicing / Modification

Q9: Series me slice assignment kaise karte hain?
A:

s[:3] = 20   # first 3 elements ka value = 20


Q10: Single element modify kaise karte hain?

s['A'] = 100  # label 'A' ka value change

4️⃣ Vectorized Operations

Q11: Arithmetic operations kaise kaam karte hain?

s + 10    # add 10 to each element
s / 10    # divide each element by 10
s * 10    # multiply each element by 10


Q12: Boolean filtering example?

s[s < 30]  # returns elements where value < 30

5️⃣ Aggregation / Statistics

Q13: Sum, mean, max, min kaise nikalte hain?

s.sum()
s.mean()
s.max()
s.min()


Q14: NaN values ke saath aggregation ka behavior?
A: Pandas automatically ignore NaN in aggregation functions.

6️⃣ Series Arithmetic & Alignment

Q15: s1 + s2 kaise kaam karta hai?
A:

Index same → corresponding elements add honge

Index mismatch → result = NaN for mismatched labels

Example:

s1 = pd.Series([20,20,20], index=['A','B','C'])
s2 = pd.Series([34,45,78], index=['A','B','C'])
s1 + s2
# A 54, B 65, C 98

7️⃣ Errors / Debugging

Q16: pd.series([...]) me error kyun?
A: Series ka S capital hona chahiye → pd.Series([...])

Q17: s1[-2] custom index me kyun error deta hai?
A: Pandas direct indexing by default label-based hota hai.

Custom labels me -2 exist nahi karta → ERROR

Correct: s1.iloc[-2]

✅ Extra Tip for Notes:

Always remember: Default index = 0,1,2…

Custom index → use .loc

Integer position → use .iloc

Boolean filtering, vectorized operations, aggregation → common in interviews

| Access                 | Result                       |
| ---------------------- | ---------------------------- |
| `df['salary']`         | Series                       |
| `df[['salary','age']]` | DataFrame                    |
| `df.iloc[:,0]`         | First column as Series       |
| `df.iloc[:,:3]`        | First 3 columns as DataFrame |

## Dataframe

In [49]:
df = pd.DataFrame({
    'salary':np.random.randint(30,90,20),
    'age':np.random.randint(23,36,20),
    'height':np.random.randint(120,190,20),
    'weight':np.random.randint(40,98,20),
    'gender':np.random.choice(['male' , 'female'],20),
    'country':np.random.choice(['aus', 'india' , 'china' , 'usa'],20)
})
df

    salary  age  height  weight  gender country
0       36   23     188      55    male     aus
1       77   33     138      43    male     aus
2       35   33     140      82  female   china
3       63   34     170      60    male   china
4       36   35     182      50  female     aus
5       74   24     140      53  female   india
6       45   31     180      46  female     usa
7       76   29     128      44    male     aus
8       65   26     160      64  female     usa
9       30   25     179      78  female   india
10      81   27     127      62  female   china
11      33   35     165      63    male     aus
12      59   25     176      61    male     aus
13      83   24     151      96    male     aus
14      75   34     131      73  female   india
15      60   32     153      59    male   india
16      59   35     141      81  female     usa
17      75   27     152      71    male   china
18      80   27     174      56  female     usa
19      41   25     160      54    male     usa

In [ ]:
df.info() #Column names, data types (int64, object)

          #Non-null counts → missing data check karne ke liye

          #Memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   salary   20 non-null     int32
 1   age      20 non-null     int32
 2   height   20 non-null     int32
 3   weight   20 non-null     int32
 4   gender   20 non-null     object
 5   country  20 non-null     object
dtypes: int32(4), object(2)
memory usage: 772.0+ bytes

In [51]:
df.describe()  #Numeric columns ka summary statistics: count, mean, std, min, 25%, 50%, 75%, max
                #Non-numeric columns ignore ho jaate hain

          salary        age      height     weight
count  20.000000  20.000000   20.000000  20.000000
mean   59.150000  29.200000  156.750000  62.550000
std    18.601853   4.335897   19.450003  13.960376
min    30.000000  23.000000  127.000000  43.000000
25%    39.750000  25.000000  140.000000  53.750000
50%    61.500000  28.000000  156.500000  60.500000
75%    75.250000  33.250000  174.500000  71.500000
max    83.000000  35.000000  188.000000  96.000000

In [ ]:
df.head(7)   # Top 7 rows show karega

             # Default = 5 rows agar number na diya ho

   salary  age  height  weight  gender country
0      77   30     175      87  female   india
1      35   33     131      41  female     aus
2      37   28     184      57  female   china
3      55   26     158      89    male     aus
4      77   30     139      68  female   india
5      57   30     180      78    male     usa
6      41   28     133      93    male     usa

In [ ]:
df.tail()   # Bottom 5 rows show karega by default

            # df.tail(3) → last 3 rows

    salary  age  height  weight  gender country
15      40   31     148      86  female     aus
16      39   31     187      96  female     usa
17      56   25     144      53    male   india
18      49   35     177      83    male   india
19      56   25     177      46    male   india

In [ ]:
df

    salary  age  height  weight  gender country
0       77   30     175      87  female   india
1       35   33     131      41  female     aus
2       37   28     184      57  female   china
3       55   26     158      89    male     aus
4       77   30     139      68  female   india
5       57   30     180      78    male     usa
6       41   28     133      93    male     usa
7       52   34     178      43    male     usa
8       39   28     177      72  female     aus
9       34   24     160      78  female   india
10      82   34     163      46    male   china
11      54   31     173      61  female   india
12      39   33     155      40  female   india
13      60   30     126      89  female   india
14      46   25     120      70  female   china
15      40   31     148      86  female     aus
16      39   31     187      96  female     usa
17      56   25     144      53    male   india
18      49   35     177      83    male   india
19      56   25     177      46    male   india

In [ ]:
df['salary']

0     77
1     35
2     37
3     55
4     77
5     57
6     41
7     52
8     39
9     34
10    82
11    54
12    39
13    60
14    46
15    40
16    39
17    56
18    49
19    56
Name: salary, dtype: int32

In [ ]:
df['country']  # single column --> series

0     india
1       aus
2     china
3       aus
4     india
5       usa
6       usa
7       usa
8       aus
9     india
10    china
11    india
12    india
13    india
14    china
15      aus
16      usa
17    india
18    india
19    india
Name: country, dtype: object

In [ ]:
df[['height','salary','weight']]  # ---> multiple columns --> datframe

    height  salary  weight
0      175      77      87
1      131      35      41
2      184      37      57
3      158      55      89
4      139      77      68
5      180      57      78
6      133      41      93
7      178      52      43
8      177      39      72
9      160      34      78
10     163      82      46
11     173      54      61
12     155      39      40
13     126      60      89
14     120      46      70
15     148      40      86
16     187      39      96
17     144      56      53
18     177      49      83
19     177      56      46

In [ ]:
df

    salary  age  height  weight  gender country
0       77   30     175      87  female   india
1       35   33     131      41  female     aus
2       37   28     184      57  female   china
3       55   26     158      89    male     aus
4       77   30     139      68  female   india
5       57   30     180      78    male     usa
6       41   28     133      93    male     usa
7       52   34     178      43    male     usa
8       39   28     177      72  female     aus
9       34   24     160      78  female   india
10      82   34     163      46    male   china
11      54   31     173      61  female   india
12      39   33     155      40  female   india
13      60   30     126      89  female   india
14      46   25     120      70  female   china
15      40   31     148      86  female     aus
16      39   31     187      96  female     usa
17      56   25     144      53    male   india
18      49   35     177      83    male   india
19      56   25     177      46    male   india

In [ ]:
df[0] #Pandas try karega column label 0 dhundne ki → exist nahi karta → ERROR
      #Yahan 0 column name nahi hai (columns = 'salary','age','height','weight','gender','country')
      # issa access karna ka liya muja iloc ka use karna hoga

KeyError: 0

## Indexing and Slicing on dataframe
   iloc

      int location / int index


      df.iloc[row_slicing, col_slicing]

    loc


       label index

       df.loc[row_slicing, col_slicing]

In [ ]:
df

    salary  age  height  weight  gender country
0       77   30     175      87  female   india
1       35   33     131      41  female     aus
2       37   28     184      57  female   china
3       55   26     158      89    male     aus
4       77   30     139      68  female   india
5       57   30     180      78    male     usa
6       41   28     133      93    male     usa
7       52   34     178      43    male     usa
8       39   28     177      72  female     aus
9       34   24     160      78  female   india
10      82   34     163      46    male   china
11      54   31     173      61  female   india
12      39   33     155      40  female   india
13      60   30     126      89  female   india
14      46   25     120      70  female   china
15      40   31     148      86  female     aus
16      39   31     187      96  female     usa
17      56   25     144      53    male   india
18      49   35     177      83    male   india
19      56   25     177      46    male   india

In [ ]:
for i in range(65,65+20):
    print(chr(i))

A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T

In [ ]:
[chr(i) for i in range(65,65+20)] # list comprehendion aak list banegi

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T']

In [ ]:
df = pd.DataFrame({
    'salary' : np.random.randint(30,90,20),
    'age' : np.random.randint(23,36,20),
    'height' : np.random.randint(120,190,20),
    'weight' : np.random.randint(40,98,20),
    'gender' : np.random.choice(['female' , 'male'], 20),
    'country' : np.random.choice(['aus','india','china','usa'],20),
}, index = [chr(i) for i in range(65,65+20)])
df

   salary  age  height  weight  gender country
A      64   23     182      59  female     aus
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
D      53   28     157      41    male   china
E      47   33     172      68    male     aus
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china

In [ ]:
df.iloc[2:10:2 , ::2] #Rows: 2:10:2 → 2nd to 9th row, step = 2 → 2,4,6,8

                      #Columns: ::2 → all columns, step = 2 → 0,2,4

                      #Output → subset of rows & columns

                     # Note: .iloc = integer position indexing

   salary  height  gender
C      87     181  female
E      47     172    male
G      60     150    male
I      68     136  female

In [ ]:
df

   salary  age  height  weight  gender country
A      64   23     182      59  female     aus
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
D      53   28     157      41    male   china
E      47   33     172      68    male     aus
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china

In [ ]:
df.loc['B':'K':3 , 'salary':'weight']  # Rows: 'B':'K':3 → labels from 'B' to 'K', step = 3 → 'B','E','H','K'

                                       # Columns: 'salary':'weight' → from 'salary' to 'weight' inclusive

                                       # .loc = label-based indexing

   salary  age  height  weight
B      70   31     151      55
E      47   33     172      68
H      49   30     128      68
K      56   25     128      91

In [ ]:
df

   salary  age  height  weight  gender country
A      64   23     182      59  female     aus
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
D      53   28     157      41    male   china
E      47   33     172      68    male     aus
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china

In [ ]:
df.iloc[0,0]    # first row, first col (salary of 'A)

np.int32(64)

In [ ]:
df.iloc[0,0] = 57   # update that value

In [ ]:
df

   salary  age  height  weight  gender country
A      57   23     182      59  female     aus
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
D      53   28     157      41    male   china
E      47   33     172      68    male     aus
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china

In [ ]:
df.iloc[2:5, [4,5]]      # Rows 2,3,4 (3 rows)

                        # Columns index 4 & 5 → 'gender','country'

   gender country
C  female     usa
D    male   china
E    male     aus

In [ ]:
df.iloc[2:5, [4,5]] = [['female' , 'usa'],['male' , 'india'], ['male' , 'india']]

Replace multiple values at once

Shape of RHS must match shape of selected subset

In [ ]:
df

   salary  age  height  weight  gender country
A      57   23     182      59  female     aus
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
D      53   28     157      41    male   india
E      47   33     172      68    male   india
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china

In [ ]:
df[df['country'] == 'india']

   salary  age  height  weight  gender country
D      53   28     157      41    male   india
E      47   33     172      68    male   india
P      66   31     145      49    male   india
Q      67   27     126      86  female   india

In [ ]:
df[(df['country'] == 'india') & (df['salary'] > 50)]
# Multiple conditions → & = AND
# Rows where country='india' AND salary>50

   salary  age  height  weight  gender country
D      53   28     157      41    male   india
P      66   31     145      49    male   india
Q      67   27     126      86  female   india

In [ ]:
df

   salary  age  height  weight  gender country
A      57   23     182      59  female     aus
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
D      53   28     157      41    male   india
E      47   33     172      68    male   india
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china

In [ ]:
df.query("country == 'india' and salary > 50 ")
# .query() → alternate, readable syntax

# Can use variables:

   salary  age  height  weight  gender country
D      53   28     157      41    male   india
P      66   31     145      49    male   india
Q      67   27     126      86  female   india

In [ ]:
country = input("Enter  name: ")
salary = int(input('Enter a salary: '))

In [ ]:
df.query("country==@country and salary > @salary")
# rows ko filter karna ka liya jahan condition match ho
# @variable Python varible ko query mein use karna ka liya

   salary  age  height  weight  gender country
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
G      60   23     150      56    male     usa
M      51   23     139      46    male     usa

In [ ]:
df

   salary  age  height  weight  gender country
A      57   23     182      59  female     aus
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
D      53   28     157      41    male   india
E      47   33     172      68    male   india
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china

In [ ]:
df['new'] = np.random.randint(23,56,20)  # new column : 'new is added with 20 random integers

In [ ]:
df

   salary  age  height  weight  gender country  new
A      57   23     182      59  female     aus   43
B      70   31     151      55  female     usa   34
C      87   35     181      76  female     usa   24
D      53   28     157      41    male   india   43
E      47   33     172      68    male   india   27
F      33   33     156      40    male     aus   50
G      60   23     150      56    male     usa   40
H      49   30     128      68  female     aus   49
I      68   33     136      78  female   china   35
J      66   25     149      97    male     aus   53
K      56   25     128      91  female   china   42
L      55   30     177      76    male   china   47
M      51   23     139      46    male     usa   38
N      68   34     159      46    male   china   31
O      34   27     187      40  female     aus   39
P      66   31     145      49    male   india   41
Q      67   27     126      86  female   india   43
R      60   24     128      45    male     aus   35
S      82   24     146      83    male   china   31
T      85   35     151      66    male   china   24

In [ ]:
df.loc['T']

salary        85
age           35
height       151
weight        66
gender      male
country    china
new           24
Name: T, dtype: object

In [ ]:
df.loc['U'] = [34,23,145,56, 'male' , 'india' , 45]

In [ ]:
df

   salary  age  height  weight  gender country  new
A      57   23     182      59  female     aus   43
B      70   31     151      55  female     usa   34
C      87   35     181      76  female     usa   24
D      53   28     157      41    male   india   43
E      47   33     172      68    male   india   27
F      33   33     156      40    male     aus   50
G      60   23     150      56    male     usa   40
H      49   30     128      68  female     aus   49
I      68   33     136      78  female   china   35
J      66   25     149      97    male     aus   53
K      56   25     128      91  female   china   42
L      55   30     177      76    male   china   47
M      51   23     139      46    male     usa   38
N      68   34     159      46    male   china   31
O      34   27     187      40  female     aus   39
P      66   31     145      49    male   india   41
Q      67   27     126      86  female   india   43
R      60   24     128      45    male     aus   35
S      82   24     146      83    male   china   31
T      85   35     151      66    male   china   24
U      34   23     145      56    male   india   45

In [ ]:
df.loc['U']

salary        34
age           23
height       145
weight        56
gender      male
country    india
new           45
Name: U, dtype: object

In [ ]:
df.loc['V'] = [34,23,145,56,'female','usa',45]

In [ ]:
df

   salary  age  height  weight  gender country  new
A      57   23     182      59  female     aus   43
B      70   31     151      55  female     usa   34
C      87   35     181      76  female     usa   24
D      53   28     157      41    male   india   43
E      47   33     172      68    male   india   27
F      33   33     156      40    male     aus   50
G      60   23     150      56    male     usa   40
H      49   30     128      68  female     aus   49
I      68   33     136      78  female   china   35
J      66   25     149      97    male     aus   53
K      56   25     128      91  female   china   42
L      55   30     177      76    male   china   47
M      51   23     139      46    male     usa   38
N      68   34     159      46    male   china   31
O      34   27     187      40  female     aus   39
P      66   31     145      49    male   india   41
Q      67   27     126      86  female   india   43
R      60   24     128      45    male     aus   35
S      82   24     146      83    male   china   31
T      85   35     151      66    male   china   24
U      34   23     145      56    male   india   45
V      34   23     145      56  female     usa   45

| Concept                | Example / Explanation                                         |
| ---------------------- | ------------------------------------------------------------- |
| `.iloc`                | Position-based indexing                                       |
| `.loc`                 | Label-based indexing                                          |
| Slicing rows & columns | `df.iloc[2:5, [0,1]]` or `df.loc['B':'K', 'salary':'weight']` |
| Filtering              | `df[df['country']=='india']`                                  |
| Modifying values       | `df.iloc[0,0]=57`                                             |
| Adding column          | `df['new']=values`                                            |
| Adding row             | `df.loc['U'] = [...]`                                         |
| `.query()`             | Condition-based filtering with variables                      |

💡 Notes Tips:

.iloc → always integers

.loc → always labels

.query() → nice for readable filtering

@variable → Python variable inside query string

and / or → combine multiple conditions

Use case → dynamic filtering, user input based search

## Drop

column wise operation perform karna ha toh [axis = 1]

row wise operation perform karna ha toh [axis = 0]

In [ ]:
df

   salary  age  height  weight  gender country  new
A      57   23     182      59  female     aus   43
B      70   31     151      55  female     usa   34
C      87   35     181      76  female     usa   24
D      53   28     157      41    male   india   43
E      47   33     172      68    male   india   27
F      33   33     156      40    male     aus   50
G      60   23     150      56    male     usa   40
H      49   30     128      68  female     aus   49
I      68   33     136      78  female   china   35
J      66   25     149      97    male     aus   53
K      56   25     128      91  female   china   42
L      55   30     177      76    male   china   47
M      51   23     139      46    male     usa   38
N      68   34     159      46    male   china   31
O      34   27     187      40  female     aus   39
P      66   31     145      49    male   india   41
Q      67   27     126      86  female   india   43
R      60   24     128      45    male     aus   35
S      82   24     146      83    male   china   31
T      85   35     151      66    male   china   24
U      34   23     145      56    male   india   45
V      34   23     145      56  female     usa   45

In [ ]:
df.drop('new')

KeyError: "['new'] not found in axis"

In [ ]:
df

   salary  age  height  weight  gender country  new
A      57   23     182      59  female     aus   43
B      70   31     151      55  female     usa   34
C      87   35     181      76  female     usa   24
D      53   28     157      41    male   india   43
E      47   33     172      68    male   india   27
F      33   33     156      40    male     aus   50
G      60   23     150      56    male     usa   40
H      49   30     128      68  female     aus   49
I      68   33     136      78  female   china   35
J      66   25     149      97    male     aus   53
K      56   25     128      91  female   china   42
L      55   30     177      76    male   china   47
M      51   23     139      46    male     usa   38
N      68   34     159      46    male   china   31
O      34   27     187      40  female     aus   39
P      66   31     145      49    male   india   41
Q      67   27     126      86  female   india   43
R      60   24     128      45    male     aus   35
S      82   24     146      83    male   china   31
T      85   35     151      66    male   china   24
U      34   23     145      56    male   india   45
V      34   23     145      56  female     usa   45

In [ ]:
df.drop('new' , axis = 1 , inplace = True)

inplace=True → original DataFrame ko modify kar do

Without inplace=True, drop sirf temporary return value deta hai, df unchanged rehta hai

In [ ]:
df

   salary  age  height  weight  gender country
A      57   23     182      59  female     aus
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
D      53   28     157      41    male   india
E      47   33     172      68    male   india
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china
U      34   23     145      56    male   india
V      34   23     145      56  female     usa

In [ ]:
df.drop(['A','B','C'],axis = 0)

   salary  age  height  weight  gender country
D      53   28     157      41    male   india
E      47   33     172      68    male   india
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china
U      34   23     145      56    male   india
V      34   23     145      56  female     usa

| Operation             | Example                                | Effect                     |
| --------------------- | -------------------------------------- | -------------------------- |
| Drop a column         | `df.drop('new', axis=1)`               | Returns df without column  |
| Drop a column inplace | `df.drop('new', axis=1, inplace=True)` | Column removed permanently |
| Drop a row            | `df.drop(['A','B'], axis=0)`           | Returns df without rows    |
| Default `axis`        | 0 → row, 1 → column                    |                            |

## Cleaning and Processing

### handling the missing values

#### 1. Fill the missing values by the central tendency
#### 2. remove / drop the data which is not good idea(data loss)

In [ ]:
df

   salary  age  height  weight  gender country
A      57   23     182      59  female     aus
B      70   31     151      55  female     usa
C      87   35     181      76  female     usa
D      53   28     157      41    male   india
E      47   33     172      68    male   india
F      33   33     156      40    male     aus
G      60   23     150      56    male     usa
H      49   30     128      68  female     aus
I      68   33     136      78  female   china
J      66   25     149      97    male     aus
K      56   25     128      91  female   china
L      55   30     177      76    male   china
M      51   23     139      46    male     usa
N      68   34     159      46    male   china
O      34   27     187      40  female     aus
P      66   31     145      49    male   india
Q      67   27     126      86  female   india
R      60   24     128      45    male     aus
S      82   24     146      83    male   china
T      85   35     151      66    male   china
U      34   23     145      56    male   india
V      34   23     145      56  female     usa

In [ ]:
np.nan # pandas mein missing values

nan

In [ ]:
df['salary'].iloc[::3] = np.nan # har 3rd row ki salary = nan
df['age'].iloc[::2] = np.nan    # har 2nd row ki salary = nan
df['weight'].iloc[::5] = np.nan # har 5 row ki salary = nan

C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\2117507736.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['salary'].iloc[::3] = np.nan
C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\2117507736.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salary'].iloc[::3] = np.nan
C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\2117507736.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['age'].iloc[::2] = np.nan
C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\2117507736.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'].iloc[::2] = np.nan
C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\2117507736.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['weight'].iloc[::5] = np.nan
C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\2117507736.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weight'].iloc[::5] = np.nan

In [ ]:
df

   salary   age  height  weight  gender country
A     NaN   NaN     182     NaN  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0   NaN     181    76.0  female     usa
D     NaN  28.0     157    41.0    male   india
E    47.0   NaN     172    68.0    male   india
F    33.0  33.0     156     NaN    male     aus
G     NaN   NaN     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0   NaN     136    78.0  female   china
J     NaN  25.0     149    97.0    male     aus
K    56.0   NaN     128     NaN  female   china
L    55.0  30.0     177    76.0    male   china
M     NaN   NaN     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0   NaN     187    40.0  female     aus
P     NaN  31.0     145     NaN    male   india
Q    67.0   NaN     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S     NaN   NaN     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0   NaN     145     NaN    male   india
V     NaN  23.0     145    56.0  female     usa

check the missing values

In [ ]:
df.isna().sum()

salary      8
age        11
height      0
weight      5
gender      0
country     0
dtype: int64

In [ ]:
df.isna().sum(axis=1)

A    3
B    0
C    1
D    1
E    1
F    1
G    2
H    0
I    1
J    1
K    2
L    0
M    2
N    0
O    1
P    2
Q    1
R    0
S    2
T    0
U    2
V    1
dtype: int64

In [ ]:
df

   salary   age  height  weight  gender country
A     NaN   NaN     182     NaN  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0   NaN     181    76.0  female     usa
D     NaN  28.0     157    41.0    male   india
E    47.0   NaN     172    68.0    male   india
F    33.0  33.0     156     NaN    male     aus
G     NaN   NaN     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0   NaN     136    78.0  female   china
J     NaN  25.0     149    97.0    male     aus
K    56.0   NaN     128     NaN  female   china
L    55.0  30.0     177    76.0    male   china
M     NaN   NaN     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0   NaN     187    40.0  female     aus
P     NaN  31.0     145     NaN    male   india
Q    67.0   NaN     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S     NaN   NaN     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0   NaN     145     NaN    male   india
V     NaN  23.0     145    56.0  female     usa

In [ ]:
df.dropna(axis=1)

   height  gender country
A     182  female     aus
B     151  female     usa
C     181  female     usa
D     157    male   india
E     172    male   india
F     156    male     aus
G     150    male     usa
H     128  female     aus
I     136  female   china
J     149    male     aus
K     128  female   china
L     177    male   china
M     139    male     usa
N     159    male   china
O     187  female     aus
P     145    male   india
Q     126  female   india
R     128    male     aus
S     146    male   china
T     151    male   china
U     145    male   india
V     145  female     usa

In [ ]:
df.dropna(axis=1 , how = 'all')

   salary   age  height  weight  gender country
A     NaN   NaN     182     NaN  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0   NaN     181    76.0  female     usa
D     NaN  28.0     157    41.0    male   india
E    47.0   NaN     172    68.0    male   india
F    33.0  33.0     156     NaN    male     aus
G     NaN   NaN     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0   NaN     136    78.0  female   china
J     NaN  25.0     149    97.0    male     aus
K    56.0   NaN     128     NaN  female   china
L    55.0  30.0     177    76.0    male   china
M     NaN   NaN     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0   NaN     187    40.0  female     aus
P     NaN  31.0     145     NaN    male   india
Q    67.0   NaN     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S     NaN   NaN     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0   NaN     145     NaN    male   india
V     NaN  23.0     145    56.0  female     usa

In [ ]:
df.dropna(axis = 0, how = 'any')

   salary   age  height  weight  gender country
B    70.0  31.0     151    55.0  female     usa
H    49.0  30.0     128    68.0  female     aus
L    55.0  30.0     177    76.0    male   china
N    68.0  34.0     159    46.0    male   china
R    60.0  24.0     128    45.0    male     aus
T    85.0  35.0     151    66.0    male   china

In [ ]:
df.dropna(axis = 0 , how = 'all')

   salary   age  height  weight  gender country
A     NaN   NaN     182     NaN  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0   NaN     181    76.0  female     usa
D     NaN  28.0     157    41.0    male   india
E    47.0   NaN     172    68.0    male   india
F    33.0  33.0     156     NaN    male     aus
G     NaN   NaN     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0   NaN     136    78.0  female   china
J     NaN  25.0     149    97.0    male     aus
K    56.0   NaN     128     NaN  female   china
L    55.0  30.0     177    76.0    male   china
M     NaN   NaN     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0   NaN     187    40.0  female     aus
P     NaN  31.0     145     NaN    male   india
Q    67.0   NaN     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S     NaN   NaN     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0   NaN     145     NaN    male   india
V     NaN  23.0     145    56.0  female     usa

In [ ]:
df

   salary   age  height  weight  gender country
A     NaN   NaN     182     NaN  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0   NaN     181    76.0  female     usa
D     NaN  28.0     157    41.0    male   india
E    47.0   NaN     172    68.0    male   india
F    33.0  33.0     156     NaN    male     aus
G     NaN   NaN     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0   NaN     136    78.0  female   china
J     NaN  25.0     149    97.0    male     aus
K    56.0   NaN     128     NaN  female   china
L    55.0  30.0     177    76.0    male   china
M     NaN   NaN     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0   NaN     187    40.0  female     aus
P     NaN  31.0     145     NaN    male   india
Q    67.0   NaN     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S     NaN   NaN     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0   NaN     145     NaN    male   india
V     NaN  23.0     145    56.0  female     usa

### fillna

In [ ]:
df

   salary   age  height  weight  gender country
A     NaN   NaN     182     NaN  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0   NaN     181    76.0  female     usa
D     NaN  28.0     157    41.0    male   india
E    47.0   NaN     172    68.0    male   india
F    33.0  33.0     156     NaN    male     aus
G     NaN   NaN     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0   NaN     136    78.0  female   china
J     NaN  25.0     149    97.0    male     aus
K    56.0   NaN     128     NaN  female   china
L    55.0  30.0     177    76.0    male   china
M     NaN   NaN     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0   NaN     187    40.0  female     aus
P     NaN  31.0     145     NaN    male   india
Q    67.0   NaN     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S     NaN   NaN     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0   NaN     145     NaN    male   india
V     NaN  23.0     145    56.0  female     usa

In [ ]:
df['salary'].fillna(df['salary'].median(), inplace = True)
df['age'].fillna(df['age'].median(), inplace = True )
df['weight'].fillna(df['weight'].median(), inplace = True)

C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\4084778916.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salary'].fillna(df['salary'].median(), inplace = True)
C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\4084778916.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace = True )
C:\Users\Anjali\AppData\Local\Temp\ipykernel_22084\4084778916.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weight'].fillna(df['weight'].median(), inplace = True)

In [ ]:
df

   salary   age  height  weight  gender country
A    58.0  30.0     182    66.0  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0  30.0     181    76.0  female     usa
D    58.0  28.0     157    41.0    male   india
E    47.0  30.0     172    68.0    male   india
F    33.0  33.0     156    66.0    male     aus
G    58.0  30.0     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0  30.0     136    78.0  female   china
J    58.0  25.0     149    97.0    male     aus
K    56.0  30.0     128    66.0  female   china
L    55.0  30.0     177    76.0    male   china
M    58.0  30.0     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0  30.0     187    40.0  female     aus
P    58.0  31.0     145    66.0    male   india
Q    67.0  30.0     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S    58.0  30.0     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0  30.0     145    66.0    male   india
V    58.0  23.0     145    56.0  female     usa

In [ ]:
df.isna().sum()

salary     0
age        0
height     0
weight     0
gender     0
country    0
dtype: int64

| Step                     | Command / Method                                     | Purpose                           |
| ------------------------ | ---------------------------------------------------- | --------------------------------- |
| Introduce missing values | `df['col'].iloc[...] = np.nan`                       | Example / testing                 |
| Check missing values     | `df.isna().sum()`                                    | Column-wise                       |
| Drop columns             | `df.dropna(axis=1, how='any/all')`                   | Remove columns with NaN           |
| Drop rows                | `df.dropna(axis=0, how='any/all')`                   | Remove rows with NaN              |
| Fill missing values      | `df['col'].fillna(df['col'].median(), inplace=True)` | Replace NaN with central tendency |

## Group by

In [ ]:
df

   salary   age  height  weight  gender country
A    58.0  30.0     182    66.0  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0  30.0     181    76.0  female     usa
D    58.0  28.0     157    41.0    male   india
E    47.0  30.0     172    68.0    male   india
F    33.0  33.0     156    66.0    male     aus
G    58.0  30.0     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0  30.0     136    78.0  female   china
J    58.0  25.0     149    97.0    male     aus
K    56.0  30.0     128    66.0  female   china
L    55.0  30.0     177    76.0    male   china
M    58.0  30.0     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0  30.0     187    40.0  female     aus
P    58.0  31.0     145    66.0    male   india
Q    67.0  30.0     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S    58.0  30.0     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0  30.0     145    66.0    male   india
V    58.0  23.0     145    56.0  female     usa

In [ ]:
df[df['country'] == 'india']['salary'].mean()

np.float64(52.8)

In [ ]:
df[df['country'] == 'india'][['salary' , 'age' , 'height' , 'weight']].mean()

salary     52.8
age        29.8
height    149.0
weight     65.4
dtype: float64

In [ ]:
df[df['country']=='usa'][['salary','age','height','weight']].mean()

salary     66.2
age        28.8
height    153.2
weight     57.8
dtype: float64

In [ ]:
df

   salary   age  height  weight  gender country
A    58.0  30.0     182    66.0  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0  30.0     181    76.0  female     usa
D    58.0  28.0     157    41.0    male   india
E    47.0  30.0     172    68.0    male   india
F    33.0  33.0     156    66.0    male     aus
G    58.0  30.0     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0  30.0     136    78.0  female   china
J    58.0  25.0     149    97.0    male     aus
K    56.0  30.0     128    66.0  female   china
L    55.0  30.0     177    76.0    male   china
M    58.0  30.0     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0  30.0     187    40.0  female     aus
P    58.0  31.0     145    66.0    male   india
Q    67.0  30.0     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S    58.0  30.0     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0  30.0     145    66.0    male   india
V    58.0  23.0     145    56.0  female     usa

In [ ]:
df.groupby('country')

In [ ]:
df.groupby('country').groups

{'aus': ['A', 'F', 'H', 'J', 'O', 'R'], 'china': ['I', 'K', 'L', 'N', 'S', 'T'], 'india': ['D', 'E', 'P', 'Q', 'U'], 'usa': ['B', 'C', 'G', 'M', 'V']}

In [ ]:
df.groupby('country')[['age','salary']].mean()

               age     salary
country
aus      28.666667  48.666667
china    31.500000  65.000000
india    29.800000  52.800000
usa      28.800000  66.200000

In [ ]:
df.groupby('country')[['age','salary','height','weight']].mean()

               age     salary  height     weight
country
aus      28.666667  48.666667   155.0  63.666667
china    31.500000  65.000000   149.5  69.166667
india    29.800000  52.800000   149.0  65.400000
usa      28.800000  66.200000   153.2  57.800000

In [ ]:
df

   salary   age  height  weight  gender country
A    58.0  30.0     182    66.0  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0  30.0     181    76.0  female     usa
D    58.0  28.0     157    41.0    male   india
E    47.0  30.0     172    68.0    male   india
F    33.0  33.0     156    66.0    male     aus
G    58.0  30.0     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0  30.0     136    78.0  female   china
J    58.0  25.0     149    97.0    male     aus
K    56.0  30.0     128    66.0  female   china
L    55.0  30.0     177    76.0    male   china
M    58.0  30.0     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0  30.0     187    40.0  female     aus
P    58.0  31.0     145    66.0    male   india
Q    67.0  30.0     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S    58.0  30.0     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0  30.0     145    66.0    male   india
V    58.0  23.0     145    56.0  female     usa

In [ ]:
df.groupby(['country','gender'])

In [ ]:
df.groupby(['country','gender']).groups

{('aus', 'female'): ['A', 'H', 'O'], ('aus', 'male'): ['F', 'J', 'R'], ('china', 'female'): ['I', 'K'], ('china', 'male'): ['L', 'N', 'S', 'T'], ('india', 'female'): ['Q'], ('india', 'male'): ['D', 'E', 'P', 'U'], ('usa', 'female'): ['B', 'C', 'V'], ('usa', 'male'): ['G', 'M']}

In [ ]:
df.groupby(['country','gender'])[['age','salary']].mean()

                      age     salary
country gender
aus     female  30.000000  47.000000
        male    27.333333  50.333333
china   female  30.000000  62.000000
        male    32.250000  66.500000
india   female  30.000000  67.000000
        male    29.750000  49.250000
usa     female  28.000000  71.666667
        male    30.000000  58.000000

In [ ]:
df

   salary   age  height  weight  gender country
A    58.0  30.0     182    66.0  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0  30.0     181    76.0  female     usa
D    58.0  28.0     157    41.0    male   india
E    47.0  30.0     172    68.0    male   india
F    33.0  33.0     156    66.0    male     aus
G    58.0  30.0     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0  30.0     136    78.0  female   china
J    58.0  25.0     149    97.0    male     aus
K    56.0  30.0     128    66.0  female   china
L    55.0  30.0     177    76.0    male   china
M    58.0  30.0     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0  30.0     187    40.0  female     aus
P    58.0  31.0     145    66.0    male   india
Q    67.0  30.0     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S    58.0  30.0     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0  30.0     145    66.0    male   india
V    58.0  23.0     145    56.0  female     usa

In [ ]:
df.groupby(['country', 'gender']).agg({
    'salary':'mean',
    'height':'median'
})

                   salary  height
country gender
aus     female  47.000000   182.0
        male    50.333333   149.0
china   female  62.000000   132.0
        male    66.500000   155.0
india   female  67.000000   126.0
        male    49.250000   151.0
usa     female  71.666667   151.0
        male    58.000000   144.5

In [ ]:
df.groupby(['country','gender']).agg({
    'salary':'mean',
    'height':['median' ,'mean']
})

                   salary height
                     mean median        mean
country gender
aus     female  47.000000  182.0  165.666667
        male    50.333333  149.0  144.333333
china   female  62.000000  132.0  132.000000
        male    66.500000  155.0  158.250000
india   female  67.000000  126.0  126.000000
        male    49.250000  151.0  154.750000
usa     female  71.666667  151.0  159.000000
        male    58.000000  144.5  144.500000

In [ ]:
df.groupby(['country','gender']).agg({
    'salary':'mean',
    'height':['median','mean'],
    'gender':'count'
})

                   salary height             gender
                     mean median        mean  count
country gender
aus     female  47.000000  182.0  165.666667      3
        male    50.333333  149.0  144.333333      3
china   female  62.000000  132.0  132.000000      2
        male    66.500000  155.0  158.250000      4
india   female  67.000000  126.0  126.000000      1
        male    49.250000  151.0  154.750000      4
usa     female  71.666667  151.0  159.000000      3
        male    58.000000  144.5  144.500000      2

In [2]:
data = pd.read_csv('data.csv')
data

NameError: name 'pd' is not defined

In [ ]:
data.info()

NameError: name 'data' is not defined

In [ ]:
data.isna().sum()

NameError: name 'data' is not defined

In [ ]:
data

NameError: name 'data' is not defined

In [ ]:
india = data[data['country name'] == 'India']
india

NameError: name 'data' is not defined

In [ ]:
plt.plot(india['year'], india['Log GDP per capita'], '-r^')
plt.xlabel("year", size = 15)
plt.ylabel("GDP" , size = 15)
plt.show()

NameError: name 'india' is not defined

In [ ]:
data

NameError: name 'data' is not defined

In [ ]:
data['Country name'].unique()

NameError: name 'data' is not defined

In [ ]:
data['Country name'].nunique()

NameError: name 'data' is not defined

In [ ]:
data.groupby('country name')

NameError: name 'data' is not defined

In [ ]:
data.groupby('country name').groups

NameError: name 'data' is not defined

In [ ]:
df.groupby('country name').groups.items()

KeyError: 'country name'

In [ ]:
for i in data.groupby('country name').groups.items():
    print(i)

NameError: name 'data' is not defined

In [ ]:
data.iloc[[66,67,68,69,70,71,72,73,74,75,76,77,78,79]]

NameError: name 'data' is not defined

In [ ]:
for country, idx in data.groupby('Country name').groups.items():
    print(f"Country name: {country}")
    print(f"Country idx : {idx}")
    print()

NameError: name 'data' is not defined

In [ ]:
i = (23,56)
i

(23, 56)

In [ ]:
i,j = (23,56)

In [ ]:
i

23

In [ ]:
j

56

In [ ]:
for country, idx in data.groupby('Country name').groups.items():
    d = data.iloc[idx]
    plt.figure(figsize=(14,7), dpi = 150)
    plt.plot(d['year'], d['Log GDP per capita'], '--r^')
    plt.xlabel("Year", size = 15)
    plt.ylabel("GDP", size = 15)
    plt.title(country, size = 15)
    plt.savefig(f"{country}.jpeg")
    plt.show()

NameError: name 'data' is not defined

| Concept / Method                     | Code Example                                                                | What it Does / Use Case                      | Kab Use Karte Hain                                                  |
| ------------------------------------ | --------------------------------------------------------------------------- | -------------------------------------------- | ------------------------------------------------------------------- |
| **Filter rows by column value**      | `df[df['country']=='india']`                                                | Select rows where condition is True          | Jab specific subset chahiye kisi column ke basis pe                 |
| **Filter multiple columns & mean**   | `df[df['country']=='india'][['salary','age']].mean()`                       | Column-wise mean for filtered rows           | Jab hume sirf numeric columns ka average chahiye                    |
| **GroupBy single column**            | `df.groupby('country')`                                                     | Group rows by column, returns GroupBy object | Jab data ko categories (e.g., country) ke basis pe analyse karna ho |
| **Get group indices**                | `df.groupby('country').groups`                                              | Dict of `{group_name: row_indices}`          | Kab row indices dekhni ho per group                                 |
| **Aggregate after group**            | `df.groupby('country')[['age','salary']].mean()`                            | Mean of numeric columns per group            | Jab group-wise summary chahiye                                      |
| **Group by multiple columns**        | `df.groupby(['country','gender'])[['age','salary']].mean()`                 | Mean per country-gender combination          | Jab hierarchical grouping karni ho                                  |
| **Custom aggregation**               | `df.groupby(['country','gender']).agg({'salary':'mean','height':'median'})` | Multiple aggregation functions per column    | Jab different columns pe different summary statistics chahiye       |
| **Multiple functions on one column** | `df.groupby(['country','gender']).agg({'height':['median','mean']})`        | Median & mean both for same column           | Jab ek column ka detailed analysis chahiye                          |
| **Count of rows per group**          | `df.groupby(['country','gender']).agg({'gender':'count'})`                  | Number of rows in each group                 | Jab group size check karna ho                                       |
| **Query with variables**             | `df.query("country==@country and salary>@salary")`                          | Filter rows using Python variables           | Jab dynamic / user input filtering karni ho                         |
| **Iterate over groups**              | `for country, idx in df.groupby('Country name').groups.items(): ...`        | Loop through each group                      | Jab per-group operations / plotting karni ho                        |
| **Plot per group**                   | `plt.plot(d['year'], d['Log GDP per capita'])`                              | Line plot for each country                   | Jab visual trend chahiye per group                                  |
| **Drop missing rows/columns**        | `df.dropna(axis=0, how='any')` / `df.dropna(axis=1, how='all')`             | Remove rows or columns with missing values   | Jab missing data ko ignore / remove karna ho                        |
| **Fill missing values**              | `df['salary'].fillna(df['salary'].median(), inplace=True)`                  | Replace NaN with central tendency            | Jab missing numeric data ko replace karna ho                        |
| **Check missing values**             | `df.isna().sum()` / `df.isna().sum(axis=1)`                                 | Count NaNs per column / row                  | Data cleaning step me check karne ke liye                           |
| **Access row by label**              | `df.loc['A']`                                                               | Get row by index label                       | Jab custom index row chahiye                                        |
| **Access row by position**           | `df.iloc[0]`                                                                | Get row by integer position                  | Jab position ke basis pe access chahiye                             |
| **Access column**                    | `df['salary']`                                                              | Get single column                            | Jab column-wise operation karni ho                                  |
| **Access multiple columns**          | `df[['salary','age']]`                                                      | DataFrame with selected columns              | Jab subset of columns chahiye                                       |
| **Drop column / row**                | `df.drop('new', axis=1, inplace=True)` / `df.drop(['A','B'], axis=0)`       | Delete columns or rows                       | Jab unnecessary data remove karna ho                                |

## Pivot Table

In [ ]:
data[['Country name ', 'year' , 'Log GDP per capita']]

NameError: name 'data' is not defined

In [ ]:
df

   salary   age  height  weight  gender country
A    58.0  30.0     182    66.0  female     aus
B    70.0  31.0     151    55.0  female     usa
C    87.0  30.0     181    76.0  female     usa
D    58.0  28.0     157    41.0    male   india
E    47.0  30.0     172    68.0    male   india
F    33.0  33.0     156    66.0    male     aus
G    58.0  30.0     150    56.0    male     usa
H    49.0  30.0     128    68.0  female     aus
I    68.0  30.0     136    78.0  female   china
J    58.0  25.0     149    97.0    male     aus
K    56.0  30.0     128    66.0  female   china
L    55.0  30.0     177    76.0    male   china
M    58.0  30.0     139    46.0    male     usa
N    68.0  34.0     159    46.0    male   china
O    34.0  30.0     187    40.0  female     aus
P    58.0  31.0     145    66.0    male   india
Q    67.0  30.0     126    86.0  female   india
R    60.0  24.0     128    45.0    male     aus
S    58.0  30.0     146    83.0    male   china
T    85.0  35.0     151    66.0    male   china
U    34.0  30.0     145    66.0    male   india
V    58.0  23.0     145    56.0  female     usa

In [ ]:
df.pivot_table(values=['salary', 'age', 'height'], index = 'country')

               age  height     salary
country
aus      28.666667   155.0  48.666667
china    31.500000   149.5  65.000000
india    29.800000   149.0  52.800000
usa      28.800000   153.2  66.200000

In [ ]:
df.pivot_table(values = ['salary','age','height'],index = 'country', columns = 'gender')

           age                 height                 salary
gender  female       male      female        male     female       male
country
aus       30.0  27.333333  165.666667  144.333333  47.000000  50.333333
china     30.0  32.250000  132.000000  158.250000  62.000000  66.500000
india     30.0  29.750000  126.000000  154.750000  67.000000  49.250000
usa       28.0  30.000000  159.000000  144.500000  71.666667  58.000000

In [ ]:
df.pivot_table(values = ['salary','age','height'], index = ['country','gender'])

                      age      height     salary
country gender
aus     female  30.000000  165.666667  47.000000
        male    27.333333  144.333333  50.333333
china   female  30.000000  132.000000  62.000000
        male    32.250000  158.250000  66.500000
india   female  30.000000  126.000000  67.000000
        male    29.750000  154.750000  49.250000
usa     female  28.000000  159.000000  71.666667
        male    30.000000  144.500000  58.000000

In [ ]:
new = data [['country name', 'year','Log GDP per capita']]
new

NameError: name 'data' is not defined

In [ ]:
new.pivot_table(values=['Log GDP per capita'], index = 'country name', columns='year')

NameError: name 'new' is not defined

| Parameter   | Description                                   |
| ----------- | --------------------------------------------- |
| `values`    | Numeric columns to aggregate                  |
| `index`     | Rows in the output                            |
| `columns`   | Columns in the output                         |
| `aggfunc`   | Aggregation function (default = mean)         |
| Multi-index | `index=['col1','col2']` for hierarchical rows |

Difference from GroupBy:

GroupBy → summarize data, output not reshaped

Pivot Table → summarize + reshape rows x columns